## Chargement de l'action BNPP (données de 02/2010 au 11/2020) dans un dataframe

In [20]:
import pandas as pd
prices_bnpp = pd.read_csv("action_bnpp.csv", header=0, index_col=0, na_values=-99.99)

In [22]:
 prices_bnpp.index = pd.to_datetime(prices_bnpp.index, format="%Y-%m").to_period('M')

In [23]:
prices_bnpp = prices_bnpp[["Close"]]

In [29]:
prices_bnpp.head()

Close
Date              
2010-02  53.130001
2010-03  56.860001
2010-04  52.130001
2010-05  46.294998
2010-06  44.770000

## Calcul des returns

In [ ]:
returns_bnpp = prices_bnpp.pct_change()

In [33]:
returns_bnpp.tail()

Close
Date             
2020-07 -0.035482
2020-08  0.071816
2020-09 -0.152878
2020-10 -0.036158
2020-11  0.467928

## Calcul de la VaR historique

In [45]:
import numpy as np

level = 5
values = returns_bnpp.values
hist_var = -np.percentile(values[1:], level)

In [65]:
hist_var = hist_var*100
hist_var

15.268256644261353

## Caclul de la VaR paramétique

In [79]:
from scipy.stats import norm

level = 5
z = norm.ppf(level/100)
param_var = -(returns_bnpp.mean() + z*returns_bnpp.std(ddof=0))

In [80]:
param_var = param_var["Close"]*100
param_var

15.780676926780215

## Caclul de la VaR non paramétique (Cornish-Fisher)

In [59]:
from scipy.stats import skew
from scipy.stats import kurtosis

values = returns_bnpp.values
s = skew(values[1:])
s

array([0.22033144])

In [60]:
k = kurtosis(values[1:])
k

array([3.97956097])

In [61]:
z = (z + (z**2 - 1)*s/6 + (z**3 -3*z)*(k-3)/24 - (2*z**3 - 5*z)*(s**2)/36)
z

array([-1.56154272])

In [73]:
non_param_var = -(returns_bnpp.mean() + z*returns_bnpp.std(ddof=0))
non_param_var = non_param_var["Close"]*100
non_param_var

14.964342613495385